### ISSUE TITLE
Progress bar is not updating

### ISSUE THREAD

**Issue by skoldobskiy** [mortacious/numba-progress#6]
Hello!
I wanted to take advantage of using your package.
I successfully installed it using pip, however, for the basic example 
```
import numpy as np
from numba import njit
from numba_progress import ProgressBar

num_iterations = 100

@njit(nogil=True)
def numba_function(num_iterations, progress_proxy):
    for i in range(num_iterations):
        np.random.normal(1,1,1000000)
        progress_proxy.update(1)

with ProgressBar(total=num_iterations) as progress:
    numba_function(num_iterations, progress)
```
the progress bar is not updating:
![image](https://user-images.githubusercontent.com/64313360/212709255-91953feb-2eff-471b-8b9e-e0d0c46841bd.png)
What can be possible reasons for that?

My `numba` version is 0.56.3 and I am working on Mac OS Monterey.

P.S. `tqdm` itself works normal.

**Comment by mortacious** [comment]
Hey,

i've just tried the example on my linux machine and it worked without issue:
![Screenshot from 2023-01-20 12-39-57](https://user-images.githubusercontent.com/26721490/213686853-689f9805-cbba-471e-a194-f502960e3b2f.png)



It might be a Mac OS specific problem. Do the examples work for you when you run them in the regular interpreter?

**Comment by skoldobskiy** [comment]
@mortacious 
Yes, it does work in the regular interpreter and also in IPython kernel.
Strangely, but the same IPython kernel is used in Spyder or Jypiter and it does not work there.
I'll try to ask in Spyder community what can be reason of that bug.

**Comment by mortacious** [comment]
Possibly the outputs in Spyder are buffered line by line. Since `numba-progress` uses a normal `tqdm`-progressbar internally, it is probably not a problem of this package.  Does it work with the normal `tqdm.tqdm()` progressbar?

**Comment by skoldobskiy** [comment]
Yes, standard `tqdm.tqdm` works fine.
Also I have tried to check is the same problem persists on my second machine (Windows10-based python conda installation).
The package works as expected with default python/ipython AND Jupyter (in contrary to MacOS) but does not in Spyder.

**Comment by skoldobskiy** [comment]
After some additional googling I realized that the problem is probably in interaction with `QtConsole` which is under-the-hood of Spyder terminal.
I tried to launch the example script with `QtConsole` on both machines (Mac and Windows) and it does not work. `tqdm` works fine in the same time.
