### ISSUE TITLE
numba type hinting with progress_proxy

### ISSUE THREAD

**Issue by ithakis** [mortacious/numba-progress#7]
Hi, 

I am trying to pass type hinting at my njit function. When I am using numba_progress how could I also use type hinting?

Thank you.

For example _calculate_correlation_pairs accepts the progress_bar as the documentation of numba-progress says.
```

@njit('float64[:,:](float64[:,:],float64[:,:],int64, int64, )', parallel=True)
def _calculate_correlation_pairs(ds_in : np.array, ilocs : np.array, corr_method : int = numba.int64, nan_rank : numba.int64 = 2, progress_proxy = None) -> np.array :
```

**Comment by mortacious** [comment]
The `ProgressBar`-instance is lowered into a very simplified numba-internal version of type `ProgressBarType`. So using `ProgressBar` as a type hint is sufficient as the function is supposed to be called from python. 
For the signature, you will have to use the numba type  `ProgressBarType` though (untested).

**Comment by ithakis** [comment]
Thanks for the reply.

I get a "NameError: name 'ProgressBarType' is not defined" when I pass in the signature: 'float64[:,:](float64[:,:],float64[:,:],int64, int64, ProgressBarType)'

is there a way to define it? 

Thank you

**Comment by mortacious** [comment]
The `ProgressBarType`is not imported by default. You can add it explicitly by importing it with
```py
from numba_progress.progress import ProgressBarType
```

**Comment by ithakis** [comment]
Thank you for the clarification. 
I still get NameError: name 'ProgressBarType' is not defined. When I put in the signature ProgressBarType and having imported from numba_progress.progress import ProgressBarType. 

Is there a way around this ?

Thank you

**Comment by mortacious** [comment]
That was my mistake. You actually have to use the variable `progressbar_type` in the signature which represents the actual numba type instance used internally. I've adapted one of the examples as a showcase:

```py
from sleep import usleep
import numba as nb
from numba_progress import ProgressBar
from numba_progress.progress import progressbar_type


@nb.njit((nb.int64, nb.int64, progressbar_type), nogil=True)
def numba_sleeper(num_iterations, sleep_us, progress_hook):
    for i in range(num_iterations):
        usleep(sleep_us)
        progress_hook.update(1)


if __name__ == "__main__":
    num_iterations = 30
    sleep_time_us = 250_000
    with ProgressBar(total=num_iterations, ncols=80) as numba_progress:
        numba_sleeper(num_iterations, sleep_time_us, numba_progress)
```

**Comment by ithakis** [comment]
Thanks for the clarification again. Works very good now. Also to note. Removing the quotes '' outside of the signature helped with the problem.

Thanks again
