### ISSUE TITLE
Handle multiple loops per function

### ISSUE THREAD

**Issue by dforero0896** [mortacious/numba-progress#9]
Hi, I just stumbled upon your package and find it very useful. I often compile multiple loops in a single function so I wondered if there was a way to handle different loops with one progressbar argument (I imagine it would be possible to pass multiple progressbar proxies and update them individually). Maybe a reset function or something like that.

Thanks in advance.

**Comment by mortacious** [comment]
Hey, i've just added a new `set(n)` method to the ProgressBar class. This allows to (re)set the progress bar to a specific value in both python and numba compiled functions. The change should be available in new newest version (1.1.0).
Nesting multiple ProgressBar instances is supported by tqdm out of the box.

See the new example `examples/example_nested_loops.py` for both functionalities.
